### ISSUE TITLE
Unknown directory type causes deserialization failure

### ISSUE THREAD

**Issue by singron** [workos-inc/workos-kotlin#97]
We are getting the following error:

> java.security.SignatureException: Invalid signature: Cannot deserialize value of type \`com.workos.directorysync.models.DirectoryType\` from String "onelogin scim v2.0": not one of the values accepted for Enum class: [...]

It seems like it's probably bad design to use a java enum for a dynamic field like this in a client library since java enums aren't able to represent unknown values.

**Comment by singron** [comment]
Another idea is to use one of these techniques: https://blog.wpanas.eu/posts/best-way-to-handle-unkown-enum-values-using-jackson/

**Comment by robframpton** [comment]
Thanks @singron for the report. For the time being we can add the missing type to unblock you.

The team and I will discuss potential approaches to make this more resilient in the future.

**Comment by robframpton** [comment]
v1.2.1 has been published: https://search.maven.org/artifact/com.workos/workos/1.2.1/jar

**Comment by singron** [comment]
Any update on this? The same thing happened again.
